### ISSUE TITLE
Trouble running on AWS Ubuntu 22.04.1 LTS Instance

### ISSUE THREAD

**Issue by DougLoyer** [rilldata/rill-developer#1255]
**Describe the bug**
I was able to install Rill unix on a AWS Ubuntu instance.  The UI does not function correctly.  The "add source" UI has a blank dialog window.

Console shows this message:
Server started at http://localhost:8080
/bin/sh: 1: open: not found
Error: Command failed: open http://localhost:8080
/bin/sh: 1: open: not found

    at checkExecSyncError (node:child_process:828:11)
    at Object.execSync (node:child_process:899:15)
    at execSync (pkg/prelude/bootstrap.js:2115:30)
    at StartCommand.sendActions (/snapshot/rill-developer/web-local/dist/web-local/src/cli/StartCommand.js:32:43)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async StartCommand.run (/snapshot/rill-developer/web-local/dist/web-local/src/cli/DataModelerCliCommand.js:73:9) {
  status: 127,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 2f 62 69 6e 2f 73 68 3a 20 31 3a 20 6f 70 65 6e 3a 20 6e 6f 74 20 66 6f 75 6e 64 0a>
  ],
  pid: 6149,
  stdout: <Buffer >,
  stderr: <Buffer 2f 62 69 6e 2f 73 68 3a 20 31 3a 20 6f 70 65 6e 3a 20 6e 6f 74 20 66 6f 75 6e 64 0a>

**To Reproduce**
Launch Ubuntu 22.04.1 LTS instance on AWS
Connect via ssh
Install rill using command line script.  Either last stable or nightly build
Launch - Gets error message trying to launch browser.  This is headless
Connect to port 8080.  
UI shows, but is not usable

**Expected behavior**
Should work

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.1 LTS
 - Browser Chrome

**Additional context**
Works great on Mac.  Want to host it where other people can use it, but ran into this problem.  We could use a different flavor of Linux if we knew one that worked.  What do you use for testing?

**Comment by magorlick** [comment]
Thank you for reporting this, @DougLoyer -- we are investigating what might be going on.  I think you are encountering two (or maybe more) issues.  

The first is one we are looking to fix. Right now there is a bug where we are using the `open` command to open the browser on your behalf when you run `rill start`, however it only works on mac, not linux.

The second is related to hosting Rill on AWS. Unfortunately we do not support this path at this time, but we do have some plans in the works to help you share your Rill project with others in the near future!

@nishantmonu51, could this issue reported in discord be related? It seems similar to what this user is reporting. 
https://www.loom.com/share/664656924cc5474a80772121350bb61f

As discussed internally, I would like to get this fix in for the next release. Can we please scope this work and assign it?

**Comment by magorlick** [comment]
I replicated this on codespaces.  Here is the error I am getting, the same one reported in loom, I believe.

```
@magorlick ➜ /workspaces/codespaces-blank $ rill start
Ports 8081 or 9081 already in use.
Server started at http://localhost:8080
/bin/sh: 1: open: not found
Error: Command failed: open http://localhost:8080
/bin/sh: 1: open: not found

    at checkExecSyncError (node:child_process:828:11)
    at Object.execSync (node:child_process:899:15)
    at execSync (pkg/prelude/bootstrap.js:2115:30)
    at StartCommand.sendActions (/snapshot/rill-developer/web-local/dist/web-local/src/cli/StartCommand.js:32:43)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async StartCommand.run (/snapshot/rill-developer/web-local/dist/web-local/src/cli/DataModelerCliCommand.js:73:9) {
  status: 127,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 2f 62 69 6e 2f 73 68 3a 20 31 3a 20 6f 70 65 6e 3a 20 6e 6f 74 20 66 6f 75 6e 64 0a>
  ],
  pid: 6487,
  stdout: <Buffer >,
  stderr: <Buffer 2f 62 69 6e 2f 73 68 3a 20 31 3a 20 6f 70 65 6e 3a 20 6e 6f 74 20 66 6f 75 6e 64 0a>
```

**Comment by hamilton** [comment]
@DougLoyer I believe this might have been fixed in `0.15`, which is now live. Mind checking if it works for you?

**Comment by lya01013451** [comment]
@hamilton also encountered this when run 'rill start' after install app using 'curl -s https://cdn.rilldata.com/install.sh | bash', any updates?

**Comment by eminemead** [comment]
> @DougLoyer I believe this might have been fixed in `0.15`, which is now live. Mind checking if it works for you?

I'm 0.15 and I still come across the same issue...

**Comment by magorlick** [comment]
I just tried again in codespaces and I am still getting the port error, though it seems like this [quick fix](https://github.com/rilldata/rill-developer/issues/1274) helped with the linux open error. 

I think the port error for hosting Rill is a more complicated fix. Unfortunately we do not currently support hosting Rill in this way, but we have plans to help share your analysis in the works.  @lya01013451 @eminemead ,  are you both trying to host Rill? If so, why do you want to host your project in this way? Would love to understand whether the solutions we are cooking up would help you with your issue here!

**Comment by magorlick** [comment]
We released Rill `0.16` yesterday and I just validated that we now work in linux codespaces. Give it another try when you have a chance and let me know if it works for you too @eminemead , @lya01013451 , @DougLoyer ,

https://docs.rilldata.com/using-rill/install
